"""Initial migration.

Revision ID: 000000000001
Revises:
Create Date: 2021-08-07 16:16:16.161616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "000000000001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "actors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("birthday", sa.Date(), nullable=False),
        sa.Column("sex", sa.Boolean(), nullable=False),
        sa.Column("profile_url", sa.String(length=300), nullable=True),
        sa.Column("photo_url", sa.String(length=300), nullable=True),
        sa.PrimaryKeyConstraint("id")
    )
    op.create_table(
        "genres",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id")
    )
    op.create_table(
        "languages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id")
    )
    op.create_table(
        "movies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=True),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("release_country", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id")
    )
    op.create_table(
        "movies_genres",
        sa.Column("movie_id", sa.Integer(), nullable=False),
        sa.Column("genre_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["genre_id"],
            ["genres.id"],
        ),
        sa.ForeignKeyConstraint(
            ["movie_id"],
            ["movies.id"],
        ),
        sa.PrimaryKeyConstraint("movie_id", "genre_id")
    )
    op.create_table(
        "movies_languages",
        sa.Column("movie_id", sa.Integer(), nullable=False),
        sa.Column("language_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["language_id"],
            ["languages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["movie_id"],
            ["movies.id"],
        ),
        sa.PrimaryKeyConstraint("movie_id", "language_id")
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("movies_languages")
    op.drop_table("movies_genres")
    op.drop_table("movies")
    op.drop_table("languages")
    op.drop_table("genres")
    op.drop_table("actors")
    # ### end Alembic commands ###
