name: CI For Capstone

on: 
  push:
    branches: [ master ]    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2      
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'          
      - name: Build Angular project
        run: |
          cd ./projects/04_capstone/frontend
          npm ci
          npm run ng build -- --deploy-url /static/          
      - name: Copy static files
        run: | 
          cd ./projects/04_capstone/frontend
          cp -r ./dist/capstone/* ../backend/static
          cp ./dist/capstone/index.html ../backend/templates
          rm ../backend/static/index.html      
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.x'
      - name: Instal requirements
        run: |
          cd ./projects/04_capstone/backend
          pip install -r requirements.txt          
