name: CI For Capstone

on: 
  push:
    branches: [ master ]    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2      
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'          
      - name: Build Angular project
        run: |
          cd ./projects/04_capstone/frontend
          npm ci
          npm run ng build -- --deploy-url /static/          
      - name: Copy static files
        run: | 
          cd ./projects/04_capstone/frontend
          cp -r ./dist/capstone/* ../backend/static
          cp ./dist/capstone/index.html ../backend/templates
          rm ../backend/static/index.html
      - name: Deploy changes to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "fsnd-capstone-agency"
          heroku_email: ${{secrets.HEROKU_USER_EMAIL}}
          appdir: "/projects/04_capstone/backend"
